[package]
name = "drfiley"
version = "0.1.0"
edition = "2021"

[dependencies]
bebop = "2.6.0"
config = { version = "0.13.3", features = ["toml"] }
dotenv = "0.15.0"
prost = "0.11.9"
serde = { version = "1.0.160", features = ["derive"] }
tokio = { version = "1.28.1", features = ["macros", "rt-multi-thread"] }
tonic = "0.9.2"
zmq = "0.10.0"

[lib]
name = "drfiley"
path = "src/lib.rs"

[[bin]]
name = "drfiley-agent"
path = "src/bin/drfiley-agent/main.rs"

[build-dependencies]
tonic-build = "0.9.2"

